<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Menu List</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #1a4d2e; padding-bottom: 15px; }
        .header h1 { font-size: 22px; color: #1a4d2e; margin-bottom: 5px; }
        .header p { font-size: 12px; color: #666; }
        .export-info-table { width: 100%; margin-bottom: 15px; }
        .export-info-table td { font-size: 10px; color: #555; padding: 2px 0; }
        .export-info-table td:last-child { text-align: right; }
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.data-table thead th { background-color: #1a4d2e; color: white; font-weight: bold; text-transform: uppercase; font-size: 9px; letter-spacing: 0.5px; padding: 10px 8px; text-align: center; border: 1px solid #145a32; }
        table.data-table tbody td { padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 10px; }
        table.data-table tbody tr:nth-child(even) { background-color: #f8f9fa; }
        .item-name { text-align: left; font-weight: 600; }
        .status-available { color: #1a4d2e; font-weight: bold; }
        .status-unavailable { color: #e74c3c; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
        .total-row { text-align: right; font-weight: bold; font-size: 11px; padding: 8px; color: #1a4d2e; }
    </style>
</head>
<body>
    <div class="header">
        <h1>RestoTrack - Menu List</h1>
        <p>Menu Management Report</p>
    </div>

    <table class="export-info-table">
        <tr>
            <td><strong>Exported By:</strong> {{ $exportedBy }}</td>
            <td><strong>Date Exported:</strong> {{ $exportedAt }}</td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 30%;">Menu Item</th>
                <th style="width: 15%;">Price</th>
                <th style="width: 20%;">Category</th>
                <th style="width: 15%;">Status</th>
                <th style="width: 15%;">Date Added</th>
            </tr>
        </thead>
        <tbody>
            @forelse($menus as $index => $menu)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td class="item-name">{{ $menu['name'] }}</td>
                    <td>{{ $menu['price'] }}</td>
                    <td>{{ $menu['category'] }}</td>
                    <td class="{{ $menu['status'] === 'Available' ? 'status-available' : 'status-unavailable' }}">
                        {{ $menu['status'] }}
                    </td>
                    <td>{{ $menu['date_added'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px;">No menu items found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="total-row">
        Total Menu Items: {{ count($menus) }}
    </div>

    <div class="footer">
        <p>Generated by RestoTrack &mdash; {{ $exportedAt }}</p>
    </div>
</body>
</html>
