<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Arial, sans-serif; font-size: 11px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 3px solid #1a4d2e; padding-bottom: 15px; }
        .header h1 { font-size: 22px; color: #1a4d2e; margin-bottom: 5px; }
        .header p { font-size: 12px; color: #666; }
        .export-info-table { width: 100%; margin-bottom: 15px; }
        .export-info-table td { font-size: 10px; color: #555; padding: 2px 0; }
        .export-info-table td:last-child { text-align: right; }
        table.data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        table.data-table thead th { background-color: #1a4d2e; color: white; font-weight: bold; text-transform: uppercase; font-size: 8px; letter-spacing: 0.5px; padding: 10px 6px; text-align: center; border: 1px solid #145a32; }
        table.data-table tbody td { padding: 7px 6px; border: 1px solid #ddd; text-align: center; font-size: 9px; }
        table.data-table tbody tr:nth-child(even) { background-color: #f8f9fa; }
        .item-name { text-align: left; font-weight: 600; }
        .items-cell { text-align: left; font-size: 8px; }
        .status-completed { color: #1a4d2e; font-weight: bold; }
        .status-pending { color: #e67e22; font-weight: bold; }
        .status-cancelled { color: #e74c3c; font-weight: bold; }
        .footer { margin-top: 20px; text-align: center; font-size: 9px; color: #999; border-top: 1px solid #ddd; padding-top: 10px; }
        .total-row { text-align: right; font-weight: bold; font-size: 11px; padding: 8px; color: #1a4d2e; }
    </style>
</head>
<body>
    <div class="header">
        <h1>RestoTrack - Sales Report</h1>
        <p>Order History Report</p>
        @if(!empty($dateRange))
            <p style="font-size: 13px; color: #1a4d2e; font-weight: bold; margin-top: 5px;">Period: {{ $dateRange }}</p>
        @endif
    </div>

    <table class="export-info-table">
        <tr>
            <td><strong>Exported By:</strong> {{ $exportedBy }}</td>
            <td><strong>Date Exported:</strong> {{ $exportedAt }}</td>
        </tr>
    </table>

    <table class="data-table">
        <thead>
            <tr>
                <th style="width: 3%;">#</th>
                <th style="width: 10%;">Date & Time</th>
                <th style="width: 17%;">Items</th>
                <th style="width: 8%;">Subtotal</th>
                <th style="width: 7%;">Tax</th>
                <th style="width: 8%;">Total</th>
                <th style="width: 9%;">Payment Type</th>
                <th style="width: 9%;">Customer Type</th>
                <th style="width: 8%;">Status</th>
                <th style="width: 10%;">Cashier Name</th>
                <th style="width: 11%;">Server Name</th>
            </tr>
        </thead>
        <tbody>
            @forelse($orders as $index => $order)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $order['date_time'] }}</td>
                    <td class="items-cell">{{ $order['items'] }}</td>
                    <td>{{ $order['subtotal'] }}</td>
                    <td>{{ $order['tax'] }}</td>
                    <td><strong>{{ $order['total'] }}</strong></td>
                    <td>{{ $order['payment_type'] }}</td>
                    <td>{{ $order['customer_type'] }}</td>
                    <td class="{{ $order['status'] === 'Completed' ? 'status-completed' : ($order['status'] === 'Cancelled' ? 'status-cancelled' : 'status-pending') }}">
                        {{ $order['status'] }}
                    </td>
                    <td>{{ $order['cashier_name'] }}</td>
                    <td>{{ $order['server_name'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="11" style="text-align: center; padding: 20px;">No orders found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="total-row">
        Total Orders: {{ count($orders) }}
    </div>

    <div class="footer">
        <p>Generated by RestoTrack &mdash; {{ $exportedAt }}</p>
    </div>
</body>
</html>
